# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WSD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WSD

pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJExtension', '~> 3.0.13'
pod 'Reachability', '~> 3.2'
pod 'JSPatch', '~> 1.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDAutoLayout', '~> 2.1.4'
pod 'SDCycleScrollView', '~> 1.65'
pod 'Shimmer', '~> 1.0.2'
pod 'BaiduMapKit'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'Masonry', '~> 1.0.2'
pod 'JPush', '~> 2.2.0.1'
pod 'IQKeyboardManager', '~> 4.0.8'

  target 'WSDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WSDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
